export const SERVER_DISPATCH = 'DISPATCH_SERVER'
export const DISPATCH_SUCCESS = 'SUCCESS_SERVER'
export const DISPATCH_ERROR = 'ERROR_SERVER'
export const DEFAULT = 'STATE_DEFAULT'
export const SERVER = 'api'
